version: '3'

services:
  localstack:
    image: localstack/localstack:0.12.11
    volumes:
      - ./localstack.sh:/docker-entrypoint-initaws.d/localstack.sh
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1s
