aws:
  region: us-east-1
  service-endpoint: http://localhost:4566

app:
  queue:
    product:
      name: product_queue
      url: http://localhost:4566/000000000000/product_queue
  dead-letter-queue:
    product:
      name: product_queue_dead_letter
      url: http://localhost:4566/000000000000/product_queue_dead_letter
